### ISSUE TITLE
Domácí úkol č. 1

### ISSUE THREAD

**Issue by TerezaMark** [TerezaMark/kurz-python-czechitas-2024#1]
Ahoj, do tohoto repozitáře jsem odevzdala úkol (domaci_ukol_1), děkuji za zpětnou vazbu. Tereza

**Comment by evgeniyako-edu** [comment]
Ahoj, vypada to super! Jen jedna mala drobnost

```
def add_extra(self, ingredient: str, quantity: int, price_per_ingredient: int):
            self.ingredients[ingredient] = quantity

            extra_price = quantity*price_per_ingredient
            self.price += extra_price
```
Myslim si, ze to nebude fungovat spravne, jestli nekdo prida navic ingredient, ktery uz v te pizze je (treba extra syr do margarity). Takze jeste ten extra ingredient uz je v self.ingredients, meli bychom ho mnozstvi zvysit o quantity.

Ale nemusis to opravovat, jetsli se ti nechce ;)

**Comment by TerezaMark** [comment]
Děkuju! Upravila jsem na:

@dataclass
class Pizza(Item):
    ingredients: dict

    def add_extra(self, ingredient: str, quantity: int, price_per_ingredient: int):
        if ingredient in self.ingredients:
            self.ingredients[ingredient] += quantity
        else:
            self.ingredients[ingredient] = quantity
            
    def __str__(self):
         return f"Pizza {self.name} s ingrediencemi {self.ingredients} stojí {self.price} Kč."

**Comment by evgeniyako-edu** [comment]
Super!
